-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
 
-dontwarn com.qiyukf.**
-keep class com.qiyukf.** { *; }
-dontwarn com.netease.**
-keep class com.netease.** { *; }
-dontwarn org.slf4j.**
-keep class org.slf4j.** { *; }
